// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "results",
    columns: [
      { name: "question", type: "text" },
      { name: "score", type: "int" },
      { name: "answer", type: "int" },
      { name: "uid", type: "text" },
    ],
  },
  {
    name: "users",
    columns: [
      { name: "uid", type: "text" },
      { name: "username", type: "text" },
      { name: "email", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Results = InferredTypes["results"];
export type ResultsRecord = Results & XataRecord;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type DatabaseSchema = {
  results: ResultsRecord;
  users: UsersRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Matter1626-AAA-s-workspace-rk098q.us-east-1.xata.sh/db/LCM",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
